#!/bin/bash
# Setup script to fetch agent ARN and Cognito config from AWS
# Mimics the behavior of test/connect_agent.py and test/utils.py

set -e

echo "🔧 Setting up frontend environment..."

# Check for required parameter
COGNITO_STACK_NAME=${1:-"cognito-stack-a2a"}
echo "📋 Using Cognito stack name: $COGNITO_STACK_NAME"

# Get AWS region and account ID
echo "📍 Detecting AWS region and account..."
REGION=$(aws configure get region)
if [ -z "$REGION" ]; then
    REGION="us-west-2"
    echo "⚠️  No region configured, using default: $REGION"
else
    echo "✅ Region: $REGION"
fi

ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
echo "✅ Account ID: $ACCOUNT_ID"

# Fetch host agent runtime ID from SSM
echo "📦 Fetching host agent runtime ID from SSM..."
RUNTIME_ID=$(aws ssm get-parameter --name "/hostagent/agentcore/runtime-id" --query "Parameter.Value" --output text)

if [ -z "$RUNTIME_ID" ]; then
    echo "❌ Failed to fetch runtime ID from SSM parameter: /hostagent/agentcore/runtime-id"
    echo "   Make sure the host agent is deployed and SSM parameter exists."
    exit 1
fi

echo "✅ Runtime ID: $RUNTIME_ID"

# Construct agent ARN
AGENT_ARN="arn:aws:bedrock-agentcore:${REGION}:${ACCOUNT_ID}:runtime/${RUNTIME_ID}"
echo "✅ Constructed Agent ARN: $AGENT_ARN"

# Fetch Cognito configuration from Secrets Manager
echo "🔐 Fetching Cognito configuration..."
SECRET_NAME="${COGNITO_STACK_NAME}/hostagent/client-config"
COGNITO_CONFIG=$(aws secretsmanager get-secret-value --secret-id "$SECRET_NAME" --query SecretString --output text)

if [ -z "$COGNITO_CONFIG" ]; then
    echo "❌ Failed to fetch Cognito config from secret: $SECRET_NAME"
    echo "   Make sure the Cognito stack is deployed."
    exit 1
fi

CLIENT_ID=$(echo "$COGNITO_CONFIG" | jq -r '.client_id')
TOKEN_ENDPOINT=$(echo "$COGNITO_CONFIG" | jq -r '.token_endpoint')
CLIENT_SECRET=$(echo "$COGNITO_CONFIG" | jq -r '.client_secret')

echo "✅ Cognito Client ID: $CLIENT_ID"
echo "✅ Token Endpoint: $TOKEN_ENDPOINT"

# Create .env file
echo "📝 Creating .env file..."
cat > .env << EOF
# Auto-generated by setup-env.sh
# Generated on: $(date)

# AWS Configuration
VITE_AWS_REGION=${REGION}

# Host Agent Configuration
VITE_AGENT_ARN=${AGENT_ARN}

# Cognito OAuth Configuration (M2M)
VITE_COGNITO_TOKEN_ENDPOINT=${TOKEN_ENDPOINT}
VITE_COGNITO_CLIENT_ID=${CLIENT_ID}
VITE_COGNITO_CLIENT_SECRET=${CLIENT_SECRET}
EOF

echo "✅ .env file created successfully!"
echo ""
echo "🚀 You can now run the frontend:"
echo "   npm run dev"
